### PR TITLE
Fixed spacing bug after mentions in comments

### LINKED ISSUE #2840: Add space after mentions
After inserting a mentioned user in the comment field, the cursor is positioned right after the user's name. 

We should also add space after mentions.

### PR DESCRIPTION
**Pull request by harmitgoswami**
Fix #2840 

Fixed styling bug for comments, in which there was no automatic space appended after mentioning a user using `@[name]`. The bug was resolved by explicitly setting the cursor to the end of the editor's content, thereby ensuring that the space was added in the correct location within the editor.

To reproduce results: After starting up the server, navigate to any translated string within any team/project. Then, click the "COMMENT" button on that string, and type "@[any letter]" to bring up a list of users to mention in your comment. Choose any user using either your cursor or the arrow keys + tab, then type the rest of your comment. There should be a space automatically added after the mention, before the content of your comment.

image

### CODE REVIEW

**Comment by mathjazz** [comment]
I wonder if we can avoid the edge case - if you add a mention in the middle of the comment.

**Comment by harmitgoswami** [comment]
> I wonder if we can avoid the edge case - if you add a mention in the middle of the comment.

Seems like simply adding editor to the dependency array of the useCallback did the trick :D

image

File: translate/src/modules/comments/components/AddComment.tsx [hunk 1]
```diff
@@ -108,10 +108,10 @@ export function AddComment({
         children: [{ text: name }],
       };
       Transforms.insertNodes(editor, mention);
-      Transforms.move(editor);
+      Transforms.select(editor, Editor.end(editor, []));
       Transforms.insertText(editor, ' ');
     },
-    [],
+    [editor],
```
Comment (eemeli) [inline translate/src/modules/comments/components/AddComment.tsx:114]: This addition is fine, but unnecessary in this case as the value is coming from `useMemo`.

**Review by eemeli — APPROVED** [review]

File: translate/src/modules/comments/components/AddComment.tsx (hunk 1 above)
Comment (mathjazz) [reply translate/src/modules/comments/components/AddComment.tsx:114]: So let's remove that? 

It doesn't seem to fix the problem where you add a mention in the middle of the comment - when you insert it, the space is added to the end of the string and the cursor jumps there, too.

Comment (eemeli) [reply translate/src/modules/comments/components/AddComment.tsx:114]: Including the `editor` as a dependency is nominally good practice; skipping it is such a marginal optimization that it doesn't matter. Either way goes, and neither is wrong.
