### PR TITLE
Drop support for the .lang format

### LINKED ISSUE #2132: Treat NBSP as a valid translation in .lang files
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1465824](https://bugzilla.mozilla.org/show_bug.cgi?id=1465824)
Bug Reporter: @TheoChevalier
CC:   @mathjazz

The following strings have not been synced in French: https://pontoon.mozilla.org/fr/engagement/emails/2018/fundraising_may.lang/?time=201805301102-201805311102&string=179264

I’ve tried to approve/unapprove one of them, it triggered a sync here https://pontoon.mozilla.org/sync/log/52244/ but nothing was committed.

Flod found this in the logs, Pontoon thinks it has already synced the French file https://irccloud.mozilla.com/pastebin/OdyAkbZQ/

The same strings have been translated in Polish at the same time, and have been correctly pushed: https://github.com/mozilla-l10n/engagement-l10n/commit/faa519696e9ef1253e2ffeaa00c1836fddd22972

### LINKED ISSUE #3157: Remove support for the .lang file format
We no longer use the Mozilla .lang file format at Mozilla. 

Since we're not aware of other projects using it, let's drop support for it.

Godspeed `.lang`, you've served us well!

### PR DESCRIPTION
**Pull request by eemeli**
Fixes #3157 
Closes #2132

Removing the .lang parser itself is pretty straightforward, but there are a few knock-on effects:
- Drop `parsimonious` as a dependency, as it was only used by the .lang parser
- Drop the `extra` field from translation objects, as it was only used by .lang files
- Drop the "countdown" variant of the front-end TranslationLength component, as it was only used by .lang
- Switch the "fake-checkout" `pontoon/sync/` test contents to rely on .po files instead of .lang

I'm filing this as a draft and assigning the PR to @mathjazz because I can't figure out how to fix the one remaining failing test in `pontoon/sync/tests/test_checks.py`, which relies on being able to assign an invalid value to a string in a format for which errors are stored in the database, and then makes sure that it's not incorporated into the translation memory. For now, it's marked as an expected failure. Please help?

### CODE REVIEW

File: translate/src/modules/editor/components/TranslationLength.tsx [hunk 1]
```diff
@@ -5,13 +5,7 @@ import { getPlainMessage } from '~/utils/message';
 
 import './TranslationLength.css';
 
-/**
- * Shows translation length vs. original string length, or countdown.
- *
- * Countdown is currently only supported for LANG strings, which use special
- * syntax in the comment to define maximum translation length. MAX_LENGTH
- * is provided for strings without HTML tags, so they need to be stripped.
```
Comment (mathjazz) [inline translate/src/modules/editor/components/TranslationLength.tsx:13]: It's surprising no other format supports this feature.

**Review by mathjazz — COMMENTED** [review]
Thanks! Looks good. I'll look into `test_bulk_check_invalid_translations()`.

File: translate/src/modules/editor/components/TranslationLength.tsx (hunk 1 above)
Comment (flodolo) [reply translate/src/modules/editor/components/TranslationLength.tsx:13]: I'm not surprised, but I also wonder if we should keep this around in some forms (how, given no other format has a comment/directive for max length?). We have discussed this before, from semantic comments in Fluent, to lately for CSV (LSP support).

Comment (mathjazz) [reply translate/src/modules/editor/components/TranslationLength.tsx:13]: I don't think it's feasible to keep it around. Maybe we file a generic issue and reference this PR so that we can reuse the code.

**Comment by mathjazz** [comment]
I can't push to your branch for some reason (I keep getting a username prompt), so adding a diff here:

```diff
diff --git a/pontoon/sync/tests/test_checks.py b/pontoon/sync/tests/test_checks.py
index c210736bb..538cce2be 100644
--- a/pontoon/sync/tests/test_checks.py
+++ b/pontoon/sync/tests/test_checks.py
@@ -1,8 +1,7 @@
-from unittest import expectedFailure
 from unittest.mock import patch, PropertyMock
 
 from pontoon.base.utils import aware_datetime
-from pontoon.base.tests import TranslationFactory
+from pontoon.base.tests import EntityFactory, ResourceFactory, TranslationFactory
 from pontoon.checks.models import (
     Warning,
     Error,
@@ -54,24 +53,32 @@ class TestChangesetTranslationsChecks(FakeCheckoutTestCase):
         assert not Error.objects.exists()
         assert not Warning.objects.exists()
 
-    # TODO:
-    # Removing .lang support meant removing an easy way
-    # to easily generate invalid translations.
-    @expectedFailure
     def test_bulk_check_invalid_translations(self):
         """
         Test scenario:
         * check if errors are detected
         * check if only valid translation will land in the Translate Memory
         """
+        db_resource = ResourceFactory.create(
+            project=self.db_project,
+            path="resource.ftl",
+            format="ftl",
+        )
+        db_entity = EntityFactory.create(
+            resource=db_resource,
+            string="key = Source String",
+            key="key",
+            obsolete=False,
+        )
         invalid_translation, valid_translation = TranslationFactory.create_batch(
             2,
             locale=self.translated_locale,
-            entity=self.main_db_entity,
+            entity=db_entity,
+            string="key = Translated String",
             approved=True,
             date=aware_datetime(2015, 1, 1),
         )
-        invalid_translation.string = "a\nb"
+        invalid_translation.string = "Translated String"
         invalid_translation.save()
 
         # Clear TM entries for those translations
@@ -90,7 +97,7 @@ class TestChangesetTranslationsChecks(FakeCheckoutTestCase):
         (error,) = Error.objects.all()
 
         assert error.library == FailedCheck.Library.PONTOON
-        assert error.message == "Newline characters are not allowed"
+        assert error.message == 'Expected token: "="'
         assert error.translation == invalid_translation
 
         self.changeset.translations_to_update = {

```

**Comment by mathjazz** [comment]
All tests are now passing.

**Review by mathjazz — APPROVED** [review]
