### PR TITLE
Avoid resetting errors & warning during editor mount

### LINKED ISSUE #2251: Warnings behave inconsistently when working with FTL string
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1686402](https://bugzilla.mozilla.org/show_bug.cgi?id=1686402)
Bug Reporter: @flodolo
CC:   iann_bugzilla@blueyonder.co.uk, @mathjazz
See also:     https://bugzilla.mozilla.org/show_bug.cgi?id=1618920

I can't totally figure out what's going, but this string should have a warning displayed (duplicate attribute, the error is also in the source).
https://pontoon.mozilla.org/en-GB/all-projects/all-resources/?status=warnings&string=206464

If I try to enter a new suggestion, I should get a warning that the attribute is duplicated, but it doesn't happen. The warning is displayed if I try to approve a suggestion with the error afterwards, or after I reject the suggestion.

Even worse: if I submit a suggestion, then switch to "submit" mode and submit another translation, the string gets approved without any warning.

### PR DESCRIPTION
**Pull request by eemeli**
Fixes #2251 by adding an unsaved-changes check to the failed-checks reset that's meant to only be called during editing, rather than also applying when switching between different strings.

This is a little bit of a hack as it relies on `state.unsavedchanges.exist` to change after `state.editor.translation` changes in order to handle the corner cases of going from original -> broken -> original. But 1) it works, and 2) a truly proper fix would have me refactor editor state handling completely, and that's a big enough job that we'll need to prioritise it appropriately.

### CODE REVIEW

**Comment by mathjazz** [comment]
Nice work! We need something similar in the `RichTranslationForm` component to catch cases like this:
https://pontoon.mozilla.org/fr/all-projects/all-resources/?status=warnings&string=178286

The only other issue I found is that when I click on the string in the string list for the second time, warning disappears.

**Comment by eemeli** [comment]
Changes rebased to the current `master`, and expanded to also cover `RichTranslationForm`.

To avoid the disappearing warning when re-selecting an entity from the list, that re-selection is now detected, and nothing happens then.

File: frontend/src/modules/entitieslist/components/EntitiesList.tsx [hunk 1]
```diff
@@ -197,29 +197,31 @@ export class EntitiesListBase extends React.Component<InternalProps> {
...
-                        navigation.actions.updateEntity(
-                            router,
-                            entity.pk.toString(),
-                            replaceHistory,
-                        ),
-                    );
-                },
-            ),
-        );
+        if (entity.pk !== parameters.entity) {
```
Comment (mathjazz) [inline frontend/src/modules/entitieslist/components/EntitiesList.tsx:206]: Can you invert the condition and return when true? Then you can restore the original (already pretty deep) indentation of the following block.

**Review by mathjazz — APPROVED** [review]
