### PR TITLE
Fix Request Context button Contact person mention

### LINKED ISSUE #3050: REQUEST CONTEXT or REPORT ISSUE doesn't CC project manager
Clicking focuses the COMMENTS tab, but doesn't flag the project manager.

I don't see anything related in the browser console.

### PR DESCRIPTION
**Pull request by mathjazz**
Fix #3050.

[Factoring out](https://github.com/mozilla/pontoon/commit/2f613fa74df1b04eda90bead914a2cf77faf5a0e#diff-8450f0b6e89e6e5f13e7d05d29af46988b50a0afdd034b548075dc6f8209f7a7) the `TeamComments` component broke the ability to insert the contact person via Request Context button.

### CODE REVIEW

File: translate/src/modules/entitydetails/components/Helpers.tsx [hunk 1]
```diff
@@ -182,7 +167,14 @@ export function Helpers({
               </TabPanel>
             )}
             <TabPanel>
-              <CommentsPanel />
+              <TeamComments
```
Comment (eemeli) [inline translate/src/modules/entitydetails/components/Helpers.tsx:170]:
```suggestion
              {/* HACK: Required inline due to https://github.com/mozilla/pontoon/issues/2300 */}
              <TeamComments
```

File: translate/src/modules/entitydetails/components/Helpers.tsx [hunk 2]
```diff
@@ -213,7 +205,14 @@ export function Helpers({
             </TabPanel>
           )}
           <TabPanel>
-            <CommentsPanel />
+            <TeamComments
```
Comment (eemeli) [inline translate/src/modules/entitydetails/components/Helpers.tsx:208]:
```suggestion
            {/* HACK: Required inline due to https://github.com/mozilla/pontoon/issues/2300 */}
            <TeamComments
```

**Review by eemeli — APPROVED** [review]
This hack is fine, but should make it clear that it's required due to #2300.
