### PR TITLE
Fix date format in latest activity tooltip inconsistency with the rest of the app

### LINKED ISSUE #2611: Date format in Latest activity tooltip is inconsistent with the rest of the app
Screenshot 2022-08-19 at 15 05 51

We use the same format as in the Target Date column everywhere else (History Panel, Sync Log, Profile page, etc.).

To clarify: we should use "Aug 12, 2022" instead of "12 August 2022".

### PR DESCRIPTION
**Pull request by willianveiga**
Fixes #2611.

### CODE REVIEW

File: pontoon/base/static/js/table.js [hunk 1]
```diff
@@ -9,18 +9,22 @@ $.expr[':'].containsi = function (a, i, m) {
 };
 
 /* Latest activity tooltip */
-var date_formatter = new Intl.DateTimeFormat('en-GB', {
```
Comment (mathjazz) [inline pontoon/base/static/js/table.js:12]: I'd just replace `en-GB` with `en-US` here and leave everything else as it is on master.

I'd even keep `month: 'long'`, because the space is not limited. But to be consistent, we then also need to set `month` value to `long` in `shortDateFormat` in pontoon/contributors/static/js/profile.js.

**Review by mathjazz — COMMENTED** [review]
Thanks for the patch!

Please see my in-line comment - I think we can fix the bug with much smaller changeset.

**Comment by mathjazz** [comment]
I just realized we also need to replace `en-GB` with `en-US` in pontoon/teams/static/js/bugzilla.js.

**Comment by willianveiga** [comment]
Thanks, @mathjazz.

Do we want to change `en-GB` to `en-US` [here](https://github.com/mozilla/pontoon/pull/2750/files#diff-79b6a0398959ea93fb1e1c5c9028bdfbca94d1e7d2d884a9ab3e4024e89add95L17) as well?

**Comment by mathjazz** [comment]
The current patch looks good!

> Do we want to change `en-GB` to `en-US` [here](https://github.com/mozilla/pontoon/pull/2750/files#diff-79b6a0398959ea93fb1e1c5c9028bdfbca94d1e7d2d884a9ab3e4024e89add95L17) as well?

Nice catch, let's do that and we're good!

**Review by mathjazz — APPROVED** [review]
Nice work!
