### PR TITLE
Speed up /notifications page

### LINKED ISSUE #2278: Notifications page takes forever to load, or causes application error
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1699610](https://bugzilla.mozilla.org/show_bug.cgi?id=1699610)
Bug Reporter: @flodolo
CC:   @mathjazz

My notifications page takes forever to load, and in some cases triggers an application error. I guess I'm an edge case, having too many notifications (2703 right now).

The resulting HTML is 1.65 MB, and takes 17 seconds to load.

In particular, it looks like the page has no pagination for results, which might be the main cause.

### PR DESCRIPTION
**Pull request by mathjazz**
Fix #2278.

The patch comes in 2 parts:

Part 1 improves performance by significantly reducing the number of DB calls through prefetching related data.

Part 2 improves perceived performance by only loading the first 100 notifications initially. Any remaining notifications are loaded afterwards via AJAX. That makes the page usable much faster, and by the time the user scrolls to the bottom of the page, the remaining notifications are likely to be loaded already.

### CODE REVIEW

**Comment by mathjazz** [comment]
@flodolo Could you please compare the performance of https://pontoon.mozilla.org/notifications/ and https://mozilla-pontoon-staging.herokuapp.com/notifications/ (where this patch is deployed)?

**Comment by flodolo** [comment]
On prod the document is 3.9 MB and takes on average 8s to load. 
On stage it's ~130 kB and takes about 1s, so definitely better.

Not sure I understand how that's possible, given all notifications are still there? 🤯

**Comment by mathjazz** [comment]
Thanks for testing!

See the 2nd commit message for explanation (spoiler: the request it split into two).

File: pontoon/contributors/static/js/notifications.js [hunk 1]
```diff
@@ -37,4 +39,24 @@ $(function () {
       Pontoon.markAllNotificationsAsRead();
     }, 1000);
   }
+
+  // Load remaining notifications
+  if ($('#server').data('hasMore')) {
```
Comment (eemeli) [inline pontoon/contributors/static/js/notifications.js:44]: The jQuery `.data()` does not parse the dataset contents, so that if the attribute value is `data-has-more="false"` or any other valid JSON value that's not an empty string, this condition will evaluate as true. An explicit check might be required:

```suggestion
  if ($('#server').data('hasMore') === 'true') {
```

**Review by eemeli — APPROVED** [review]
See inline quibble, otherwise looks ok.

File: pontoon/contributors/static/js/notifications.js (hunk 1 above)
Comment (mathjazz) [reply pontoon/contributors/static/js/notifications.js:44]: _Every attempt is made to convert the attribute's string value to a JavaScript value (this includes booleans, numbers, objects, arrays, and null)._

https://api.jquery.com/data/#data-html5
