### PR TITLE
Teams: fix query parameter check in bugs tab

### LINKED ISSUE #2504: Team bugs dashboard does not load when any query string is provided
STR:
1. Go to https://pontoon.mozilla.org/cs/bugs/.
2. Page loads with _Zarro Boogs Found._ (or list of bugs).
3. Go to https://pontoon.mozilla.org/cs/bugs/?foo.

What happens:
- The page loads without any bugs information.

What should happen:
- The page loads with _Zarro Boogs Found._ (or list of bugs) the same way as if without any query string.

Specifically this prevents Pontoon Add-on to include the `utm_source` for tracking.

### PR DESCRIPTION
**Pull request by functionzz**
This PR fixes the issue where one accesses the bugs tab of a teams page like `/bugs/?foo` and it returns nothing instead of `Zarro Boogs.`

Fixes #2504.

### CODE REVIEW

File: pontoon/base/static/js/tabs.js [hunk 1]
```diff
@@ -63,16 +63,15 @@ $(function () {
...
+    const tab = $('#middle .links a[href="' + path.split('?')[0] + '"]');
 
     // Update menu
     $('#middle .links li').removeClass('active');
     tab.parents('li').addClass('active');
 
     container.empty();
-
-    if (url !== '/bugs/') {
+    if (!url.startsWith('/bugs/')) {
```
Comment (mathjazz) [inline pontoon/base/static/js/tabs.js:75]: Nit: I would keep the blank line above for better readability.

**Review by mathjazz — APPROVED** [review]

**Review by mathjazz — APPROVED** [review]
