### PR TITLE
Fix #2262 - Add Time to review suggestions chart

### LINKED ISSUE #2262: Add Time to review suggestions chart to Community health dashboard
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1691770](https://bugzilla.mozilla.org/show_bug.cgi?id=1691770)
Bug Reporter: @mathjazz
Depends on:   [Bug 1687529](https://bugzilla.mozilla.org/show_bug.cgi?id=1687529)

This bug tracks the implementation of the "Time to review suggestions" chart and changes of the "Unreviewed suggestion lifespan" chart on the Community Health Dashboard.

See the spec:
https://github.com/mozilla/pontoon/blob/master/specs/0108-community-health-dashboard.md

Changes:
https://github.com/mozilla/pontoon/pull/1858

### PR DESCRIPTION
**Pull request by mathjazz**
This is a 2nd and final part to fix #2262, which adds the Time to review suggestions chart to the locale Insights tab.

As explained in ones of the commit messages, I've joined Time to review suggestions and Age of unreviewed suggestions charts into one panel. The latter is not visible by default, but that should be OK, since it's probably the least frequently used widget on the page.

The alternative to using the same panel for both charts would be to introduce a new one, which would need to be full-width in order to keep the page layout, but that's an overkill for a chart with relatively low amount of data.

The patch is deployed to stage which uses the prod DB snapshot from yesterday:
https://mozilla-pontoon-staging.herokuapp.com/it/insights/

Data migration only took a minute or so to complete.

@flodolo Could you please take it for a spin, too? Especially from the spec, UX and data perspective. I've moved the Review activity chart right next to the Time to review suggestions chart to make it easier to check the validity of the data. We can move it back to the original place if you think that works better.

### CODE REVIEW

File: pontoon/insights/static/js/insights.js [hunk 1]
```diff
@@ -183,6 +184,107 @@ var Pontoon = (function (my) {
...
+                var chart = $('#time-to-review-suggestions-chart');
+
+                new Chart(chart, {
+                    type: 'bar',
+                    data: {
+                        labels: $('#insights').data('dates'),
+                        datasets: [
+                            {
+                                type: 'line',
+                                label: 'Within a month',
```
Comment (flodolo) [inline pontoon/insights/static/js/insights.js:197]:
```suggestion
                                label: 'Within this month',
```

Since the user is hovering a month, I think it makes more sense to say `this` than `a`.

File: pontoon/insights/templates/insights/widgets/insights.html [hunk 2]
```diff
@@ -48,63 +47,59 @@ <h3 class="controls">
...
-                </canvas>
+                <div class="suggestions-age-items">
+                    <div class="suggestions-age-item time-to-review-suggestions">
+                        <h3 class="controls">
+                            Time to review suggestions
+                            {{ Tooltip.display(
+                                intro='How much time it takes on average to review a suggestion.',
+                                items=[{
+                                    'class': 'within-a-month',
+                                    'name': 'Within a month',
```
Comment (flodolo) [inline pontoon/insights/templates/insights/widgets/insights.html:60]:
```suggestion
                                    'name': 'Within this month',
```

File: pontoon/insights/templates/insights/widgets/insights.html [hunk 3]
```diff
@@ -48,63 +47,59 @@ <h3 class="controls">
...
+                                    'definition': 'Average age of suggestions reviewed during each month.',
+                                }, {
+                                    'class': 'twelve-month-average',
+                                    'name': '12-month average',
+                                    'definition': 'Average age of suggestions reviewed in the 12 months before each month.',
```
Comment (flodolo) [inline pontoon/insights/templates/insights/widgets/insights.html:65]:
```suggestion
                                    'definition': 'Average age of suggestions reviewed in the 12 months before the selected month.',
```

Not sure if `selected` is the best choice, but `hovered` might be more confusing than helping. For this one, I'm fine also to keep as-is.

**Review by flodolo — APPROVED** [review]
Thanks, the order of graphs makes sense to me.

Looking at the graphs live, I only have a few suggestions on wording. Unrelated and pre-existing: would it be possible to dismiss the infobox by clicking anywhere, instead of having to click again on the i button?

File: pontoon/insights/templates/insights/widgets/insights.html (hunk 2 above)
Comment (flodolo) [reply pontoon/insights/templates/insights/widgets/insights.html:60]: "Current month" would work for me 👍🏼

File: pontoon/insights/templates/insights/widgets/insights.html (hunk 3 above)
Comment (mathjazz) [reply pontoon/insights/templates/insights/widgets/insights.html:65]: The spec says "specific", shall we stick to that? Not sure why I changed it in first place...

File: pontoon/insights/static/css/insights.css [hunk 4]
```diff
@@ -109,6 +111,42 @@
...
+    right: 0;
+    margin-left: auto;
+    margin-right: auto;
+}
+
+#insights .suggestions-age nav ul li {
+    color: #aaaaaa;
+    cursor: pointer;
+    display: inline-block;
+}
```
Comment (eemeli) [inline pontoon/insights/static/css/insights.css:144]: This toggle ends up _tiny_. If the intent is not to hide this toggle, it needs to be bigger. Could maybe use the same style as in the bigger activity charts?

File: pontoon/insights/static/js/insights.js [hunk 5]
```diff
@@ -183,6 +191,107 @@ var Pontoon = (function (my) {
...
+                            callbacks: {
+                                label: function (items, chart) {
+                                    return (
+                                        chart.datasets[items.datasetIndex]
+                                            .label +
+                                        ': ' +
+                                        items.value +
+                                        ' days'
+                                    );
+                                },
```
Comment (eemeli) [inline pontoon/insights/static/js/insights.js:253]:
```suggestion
                                label(items, chart) {
                                    const { label } =
                                        chart.datasets[items.datasetIndex];
                                    return `${label}: ${items.value} days`;
                                },
```

File: pontoon/insights/static/js/insights.js [hunk 6]
```diff
@@ -183,6 +191,107 @@ var Pontoon = (function (my) {
...
+                                        display: false,
+                                    },
+                                    position: 'right',
+                                    ticks: {
+                                        beginAtZero: true,
+                                        maxTicksLimit: 3,
+                                        precision: 0,
+                                        callback: function (value) {
+                                            return value + ' days';
+                                        },
```
Comment (eemeli) [inline pontoon/insights/static/js/insights.js:287]:
```suggestion
                                        callback: (value) => `${value} days`,
```

File: pontoon/insights/static/js/insights.js [hunk 7]
```diff
@@ -637,3 +746,14 @@ var Pontoon = (function (my) {
...
+/* Main code */
+$(function () {
+    $('body').on('click', '#insights .suggestions-age nav li', function () {
+        var items = $('.suggestions-age nav li').removeClass('active');
+        $(this).addClass('active');
+        var index = items.index(this);
+        var itemWidth = $('.suggestions-age-item').first().outerWidth();
+        $('.suggestions-age-items').css('marginLeft', -index * itemWidth);
+    });
+});
```
Comment (eemeli) [inline pontoon/insights/static/js/insights.js:759]:
```suggestion
$('#insights .suggestions-age nav li').on('click', function () {
    var items = $('.suggestions-age nav li').removeClass('active');
    $(this).addClass('active');
    var index = items.index(this);
    var itemWidth = $('.suggestions-age-item').first().outerWidth();
    // Show the selected graph view
    $('.suggestions-age-items').css('marginLeft', -index * itemWidth);
});
```

The bundle is included at the end of the page, so there's no need to add a `$()` wrapper. Also see other suggestions in the code snippet above.

**Review by eemeli — APPROVED** [review]
Looks good. Approved pending some fix to make the toggle bigger. JS suggestions are mostly really nits.

I presume we have no active plans for adding this info to the per-project views?

File: pontoon/insights/static/js/insights.js (hunk 7 above)
Comment (mathjazz) [reply pontoon/insights/static/js/insights.js:753]: Good point. I have to keep the click event handler on the body element, though, because the Insights tab DOM is not there yet when the handler get attached.

File: pontoon/insights/static/css/insights.css (hunk 4 above)
Comment (mathjazz) [reply pontoon/insights/static/css/insights.css:144]: In the activity charts we have legends, so I worry it'll be confusing to use the same style for a different functionality. Also, chart title are long and wouldn't fit into one line.

Unless you mean we should just makes the dots bigger to match the size of the activity charts?

Comment (eemeli) [reply pontoon/insights/static/css/insights.css:144]: I don't think it'd be enough to just make the dots bigger. I think some sort of titles are needed. While there is a difference to the activity chart toggles, I don't think it's really _all_ that different?

Comment (mathjazz) [reply pontoon/insights/static/css/insights.css:144]: Screenshot 2021-12-01 at 14 24 25

Something like that? It obviously needs fine-tuning (margin etc.).

**Comment by mathjazz** [comment]
Stage updated with latest version.

File: pontoon/insights/static/css/insights.css (hunk 4 above)
Comment (eemeli) [reply pontoon/insights/static/css/insights.css]: Yes!

**Review by eemeli — APPROVED** [review]
